identifier: <%= p("gremlin.identifier").empty? ? `hostname`.strip : p("gremlin.identifier") %>
team_id: <%= p("gremlin.team_id") %>

<% if p("gremlin.team_secret") != "" %>
team_secret: <%= p("gremlin.team_secret") %>
<% else %>
team_certificate: |
<%= p("gremlin.team_certificate").to_s.gsub(/^/, "  ") %>

team_private_key: |
<%= p("gremlin.team_private_key").to_s.gsub(/^/, "  ") %>
<% end %>

<% if p("gremlin.https_proxy") != "" %>
https_proxy: <%= p("gremlin.https_proxy") %>
<% end %>

<% if p("gremlin.ssl_cert_file") != "" %>
ssl_cert_file: <%= p("gremlin.ssl_cert_file") %>
<% end %>

push_metrics:      <%= p("gremlin.push_metrics") %>
collect_processes: <%= p("gremlin.collect_processes") %>
collect_dns:       <%= p("gremlin.collect_dns") %>

<% unless p("gremlin.iam_role").empty? %>
iam_role: <%= p("gremlin.iam_role") %>
<% end %>

tags:
<% p("gremlin.tags").each do |k,v| %>
  <%= k %>: <%= v %>
<% end %>

