name: Build BOSH Release
on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install BOSH CLI
        run: |
          BOSH_CLI_VERSION=7.9.5
          curl -L "https://github.com/cloudfoundry/bosh-cli/releases/download/v${BOSH_CLI_VERSION}/bosh-cli-${BOSH_CLI_VERSION}-linux-amd64" -o bosh
          chmod +x bosh
          sudo mv bosh /usr/local/bin/bosh
          bosh --version
